name: Shell Commands
on: [push]

jobs:

  run-github-actions:

    runs-on: ubuntu-latest

    steps:

      - name: simple jason
        id: greet
        uses: actions/hello-world-java-action@v1
        with:
          who-to-greet: Sunil
      - name: Greeting time
        run: echo "${{ steps.greet.output.time}}"

