name: Actions Workflow

on:
  repository_dispatch:
    types: [build]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
       #   echo "- in ${{ github.event.inputs.home }}!"
